BACKGROUND_NOISE_REMOVED_AUDIO_DIRECTORY = "separated/mdx_extra"

FACE_IMAGE_DIRECTORY = "output/screenshots" # PATH DIR OF SAVE FRAME FROM VIDEO (DO NOT ADD / AT THE END OF PATH)
FACE_IMAGE_FILE_FORMAT = '.png'
FACE_IMAGE_INDEX_DIRECTORY = "output/image_index" # PATH DIR OF SAVE FACE EMBEDDINGS FROM SCREENSHOTS (DO NOT ADD / AT THE END OF THE PATH)
FACE_INDEX_FILE_FORMAT = '.txt'
FACE_MATCH_RESULT_CSV_PATH = "output/face_match.csv"

INPUT_VIDEO_DIRECTORY = "/Users/khasgiwa/Workbench/data-dumps/GWR/1_15" ### DIRECTORY OF VIDEO FILES (DO NOT ADD / AT THE END OF THE PATH)
INPUT_VIDEO_FILE_FORMAT = '.mp4'

TRANSCRIBED_FILE_PATH = "output/transcribe_text.csv" ### PATH OF THE OUTPUT CSV FILE
USE_FP16 = True
