BACKGROUND_NOISE_REMOVED_AUDIO_DIRECTORY = "separated/mdx_extra"
AUDIO_FILE_FORMAT = ".mp3"
BACKGROUND_REMOVED_FILE_NAME = "vocals.mp3"

FACE_IMAGE_DIRECTORY = "output/screenshots" # PATH DIR OF SAVE FRAME FROM VIDEO (DO NOT ADD / AT THE END OF PATH)
FACE_IMAGE_FILE_FORMAT = '.png'
FACE_INDEX_FILE_FORMAT = '.txt'
FACE_MATCH_RESULT_CSV_PATH = "output/face_match.csv"

INPUT_VIDEO_DIRECTORY = "/Users/jay/work/new_video" ### DIRECTORY OF VIDEO FILES (DO NOT ADD / AT THE END OF THE PATH)
INPUT_VIDEO_FILE_FORMAT = '.mp4'

TRANSCRIBED_FILE_PATH = "output/transcribe_text.csv" ### PATH OF THE OUTPUT CSV FILE
USE_FP16 = False

ONLY_UNIQUE_VIDEO_DIRECTORY = "output/unique_videos"
RENAME_FILES_DATAFRAME_PATH = "output/rename_video_files.csv"


AUDIO_EXTRACT_CSV_PATH = "output/extract_audio_from_video.csv"