BACKGROUND_NOISE_REMOVED_AUDIO_DIRECTORY = "output/audio_from_video"
BACKGROUND_NOISE_REMOVED_AUDIO_SUB_DIRECTORY = "mdx_extra"
BACKGROUND_REMOVED_FILE_NAME = "vocals.mp3"
AUDIO_FILE_FORMAT = ".mp3"

FACE_IMAGE_DIRECTORY = "output/screenshots" # PATH DIR OF SAVE FRAME FROM VIDEO (DO NOT ADD / AT THE END OF PATH)
FACE_IMAGE_FILE_FORMAT = '.png'
FACE_INDEX_FILE_FORMAT = '.txt'
FACE_MATCH_RESULT_CSV_PATH = "output/face_match.csv"

INPUT_VIDEO_DIRECTORY = "/Users/khasgiwa/Workbench/data-dumps/GWR/combined" ### DIRECTORY OF VIDEO FILES (DO NOT ADD / AT THE END OF THE PATH)
INPUT_VIDEO_FILE_FORMAT = '.mp4'

TRANSCRIBED_FILE_PATH = "output/transcribe_text.csv" ### PATH OF THE OUTPUT CSV FILE
USE_FP16 = False

AUDIO_EXTRACT_CSV_PATH = "output/extract_audio_from_video.csv"